# verify_and_manifest_001r.ps1 — PHASE5-001R: verification, preservation and custody.
#
# Measures rather than asserts. It re-parses every JSON artifact this order wrote, re-runs every builder and
# compares the regenerated bytes with the bytes on disk (so a hand-edited artifact and a non-deterministic
# builder are both caught), compares the whole workspace against the baseline taken before this order wrote
# anything, checks the content of each artifact against what the specification, verdict and order claim, and
# re-measures the read-only legacy pointers: the admitted source pin and the two consumer specimens.
# It writes preservation_and_change_record.json, file_custody_manifest.json and verification_results.json.

$ErrorActionPreference = 'Stop'
$Root = 'C:\CRP-NEW'
$Out = Join-Path $Root 'SOURCE_CAPTURES\PHASE5-001R'
$Legacy = 'C:\Users\webbd\crp-credit-app'
$Plan = 'CRP_PHASE5_STATUTE_CERTIFICATION_AND_FINDING_AUTHORIZATION_BUILD_PLAN.md'
$Narrative = 'CRP_PHASE5_001R_DETERMINISTIC_EVALUATION_SPECIFICATION_AND_GATE_5_5_VERDICT.md'
$SourcePin = 'packages\backend\src\services\legalCorpus\rules.canada.ts'
$SpecimenPrimary = 'packages\backend\fixtures\reports\equifax-david-webb.pdf'
$SpecimenSecondary = 'packages\backend\fixtures\reports\transunion-david-webb.pdf'

function Get-Sha256([string]$path) { return (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash }

$checks = New-Object System.Collections.Generic.List[object]
function Check([string]$id, [string]$what, [bool]$passed, [string]$detail) {
  $checks.Add([pscustomobject][ordered]@{ id = $id; what = $what; passed = $passed; detail = $detail })
}

$baseline = Get-Content -LiteralPath (Join-Path $Out 'preserved_files_before.json') -Raw | ConvertFrom-Json
$baselineByPath = @{}
foreach ($f in $baseline.files) { $baselineByPath[$f.relative_path] = $f }

# ---------------------------------------------------------------- preservation (measured)
$changed = New-Object System.Collections.Generic.List[object]
$missing = New-Object System.Collections.Generic.List[string]
$unchanged = 0
foreach ($f in $baseline.files) {
  $abs = Join-Path $Root $f.relative_path
  if (-not (Test-Path -LiteralPath $abs -PathType Leaf)) { $missing.Add($f.relative_path); continue }
  $now = Get-Sha256 $abs
  if ($now -eq $f.sha256) { $unchanged++ } else {
    $changed.Add([pscustomobject][ordered]@{ relative_path = $f.relative_path; before = $f.sha256; after = $now; bytes = (Get-Item -LiteralPath $abs).Length })
  }
}

# ---------------------------------------------------------------- files added by this order
$addedByThisOrder = New-Object System.Collections.Generic.List[object]
foreach ($f in (Get-ChildItem -LiteralPath $Out -File | Sort-Object Name)) {
  $addedByThisOrder.Add([pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001R\' + $f.Name; bytes = $f.Length; sha256 = Get-Sha256 $f.FullName })
}
$narrativeAbs = Join-Path $Root $Narrative
$narrativeExists = Test-Path -LiteralPath $narrativeAbs -PathType Leaf
if ($narrativeExists) {
  $addedByThisOrder.Add([pscustomobject][ordered]@{ relative_path = $Narrative; bytes = (Get-Item -LiteralPath $narrativeAbs).Length; sha256 = Get-Sha256 $narrativeAbs })
}

# The one change this order caused, disclosed by measurement: the PHASE5-001I-A suite writes its results into
# its own package when it is run, and this order ran it once before that was established. The change is
# disclosed, attributed and NOT authorised; the run has been removed from this order's builders.
$disclosedChanges = @(
  [pscustomobject][ordered]@{
    relative_path = 'SOURCE_CAPTURES\PHASE5-001I-A\test_results_001i_a.json'
    before        = 'E492041115C32857EE471389BE15B3A812D9219D655342DD64B4AAF4A8B99B22'
    after         = $null
    cause         = 'this order re-ran the PHASE5-001I-A internal test suite to measure the comparison''s "its tests pass" point. That suite''s harness writes its results into its own package (tests/harness.cjs finish()).'
    content_measured = 'the record is the same suite''s results, regenerated: 41 tests, 0 failures, ALL PHASE5-001I-A TESTS PASSED. No evidence is lost; the byte-level identity of the file is.'
    unauthorised  = $true
    authorised_by = 'nothing. This order was authorised to change no pre-existing file.'
    recurring     = 'no: the run was removed from this order''s builders, and the disclosure records the check that proves the file is now stable across builder runs.'
  }
)
$disclosedPaths = @($disclosedChanges | ForEach-Object { $_.relative_path })
foreach ($d in $disclosedChanges) {
  $measured = @($changed | Where-Object { $_.relative_path -eq $d.relative_path })
  if ($measured.Count -eq 1) { $d.after = $measured[0].after }
}
$undeclaredChanges = @($changed | Where-Object { $disclosedPaths -notcontains $_.relative_path })
$declaredButUnchanged = @($disclosedPaths | Where-Object { @($changed | ForEach-Object { $_.relative_path }) -notcontains $_ })
Check 'V-R1' 'no pre-existing file was changed by this order outside the one change it discloses' `
  ($undeclaredChanges.Count -eq 0) `
  ("changed: {0}; declared and disclosed: {1}; undeclared: {2}" -f $changed.Count, $disclosedChanges.Count, $undeclaredChanges.Count)
Check 'V-R2' 'no pre-existing file was deleted by this order' ($missing.Count -eq 0) ("missing: {0}" -f $missing.Count)
Check 'V-R20' 'every disclosed change is exactly the change that was measured, so the disclosure cannot hide anything' `
  ($declaredButUnchanged.Count -eq 0 -and @($disclosedChanges | Where-Object { $_.after -eq $null }).Count -eq 0) `
  ("disclosed but not measured as changed: {0}; disclosed entries with no measured digest: {1}" -f $declaredButUnchanged.Count, @($disclosedChanges | Where-Object { $_.after -eq $null }).Count)


# ---------------------------------------------------------------- every artifact parses, and no BOM
$jsonArtifacts = @('report_fact_model.json', 'extraction_status_vocabulary.json', 'deterministic_evaluator_specification.json',
  'output_vocabulary_and_explanation_surface.json', 'internal_determinism_check.json', 'implementation_comparison.json',
  'scoped_gate_5_5_verdict.json', 'next_work_order.json', 'input_verification.json', 'preserved_files_before.json')
$badJson = New-Object System.Collections.Generic.List[string]
$bomFound = New-Object System.Collections.Generic.List[string]
$parsed = @{}
foreach ($name in $jsonArtifacts) {
  $abs = Join-Path $Out $name
  if (-not (Test-Path -LiteralPath $abs -PathType Leaf)) { $badJson.Add($name + ' (absent)'); continue }
  $bytes = [System.IO.File]::ReadAllBytes($abs)
  if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) { $bomFound.Add($name) }
  try { $parsed[$name] = Get-Content -LiteralPath $abs -Raw | ConvertFrom-Json } catch { $badJson.Add($name + ' (' + $_.Exception.Message + ')') }
}
Check 'V-R3' 'every JSON artifact of this order parses' ($badJson.Count -eq 0) ("unparsable: {0}" -f ($badJson -join ', '))
Check 'V-R4' 'no artifact of this order carries a byte-order mark' ($bomFound.Count -eq 0) ("with BOM: {0}" -f ($bomFound -join ', '))
Check 'V-R5' 'the narrative record exists' $narrativeExists $Narrative

# ---------------------------------------------------------------- the builders regenerate the same bytes
$builders = @('build_001r_fact_model.js', 'build_001r_status_vocabulary.js', 'build_001r_evaluator_spec.js', 'build_001r_output_surface.js',
  'build_001r_determinism_check.js', 'build_001r_implementation_comparison.js', 'build_001r_gate55.js', 'build_001r_next_order.js')
$producedBy = @{
  'build_001r_fact_model.js'               = 'report_fact_model.json'
  'build_001r_status_vocabulary.js'        = 'extraction_status_vocabulary.json'
  'build_001r_evaluator_spec.js'           = 'deterministic_evaluator_specification.json'
  'build_001r_output_surface.js'           = 'output_vocabulary_and_explanation_surface.json'
  'build_001r_determinism_check.js'        = 'internal_determinism_check.json'
  'build_001r_implementation_comparison.js' = 'implementation_comparison.json'
  'build_001r_gate55.js'                   = 'scoped_gate_5_5_verdict.json'
  'build_001r_next_order.js'               = 'next_work_order.json'
}
$regeneration = New-Object System.Collections.Generic.List[object]
$regression = 0
foreach ($b in $builders) {
  $target = Join-Path $Out $producedBy[$b]
  $before = Get-Sha256 $target
  Push-Location $Root
  $null = & node (Join-Path $Out $b) 2>&1
  $exit = $LASTEXITCODE
  Pop-Location
  $after = Get-Sha256 $target
  $identical = ($before -eq $after)
  if (-not $identical -or $exit -ne 0) { $regression++ }
  $regeneration.Add([pscustomobject][ordered]@{ builder = $b; exit_code = $exit; artifact = $producedBy[$b]; sha256_before = $before; sha256_after = $after; byte_identical = $identical })
}
Check 'V-R6' 'every builder re-runs cleanly and regenerates its artifact byte-for-byte, so no artifact was hand-edited' ($regression -eq 0) ("builders with a difference or a non-zero exit: {0}" -f $regression)

# ---------------------------------------------------------------- content checks on the artifacts themselves
$factModel = $parsed['report_fact_model.json']
$statuses = $parsed['extraction_status_vocabulary.json']
$spec = $parsed['deterministic_evaluator_specification.json']
$surface = $parsed['output_vocabulary_and_explanation_surface.json']
$determinismDoc = $parsed['internal_determinism_check.json']
$comparisonDoc = $parsed['implementation_comparison.json']
$verdict = $parsed['scoped_gate_5_5_verdict.json']
$order = $parsed['next_work_order.json']
$inputs = $parsed['input_verification.json']

$kinds = @($factModel.facts | ForEach-Object { $_.kind } | Sort-Object -Unique)
Check 'V-R7' 'the fact model records two facts of two different kinds, each carrying the six parts the plan names' `
  ($factModel.facts.Count -eq 2 -and $kinds.Count -eq 2 -and $factModel.what_each_fact_record_carries.Count -eq 6) `
  ("facts: {0}; kinds: {1}; carried parts: {2}" -f $factModel.facts.Count, ($kinds -join '/'), $factModel.what_each_fact_record_carries.Count)

Check 'V-R8' 'the status vocabulary is the gate''s four, and every refusal state of the unit is named' `
  ($statuses.vocabulary_is_exact.identical -eq $true -and $statuses.statuses.Count -eq 4 -and $statuses.refusal_states.Count -eq 6) `
  ("statuses: {0}; identical to the gate line: {1}; refusal states: {2}" -f $statuses.statuses.Count, $statuses.vocabulary_is_exact.identical, $statuses.refusal_states.Count)

$conventionsAreConventions = @($spec.conventions | Where-Object { $_.is_a_requirement_of_the_text -ne $false }).Count -eq 0
Check 'V-R9' 'the specification carries the six recorded conventions as conventions, recomputes the record''s arithmetic, and withholds the boundary day' `
  ($spec.decision_rules.Count -ge 15 -and $spec.conventions.Count -eq 6 -and $conventionsAreConventions -and $spec.arithmetic_recomputed.matches_the_record -eq $true -and $spec.boundary_withheld.rule.Length -gt 0) `
  ("rules: {0}; conventions: {1}; all conventions non-requirements: {2}; arithmetic matches the record: {3}" -f $spec.decision_rules.Count, $spec.conventions.Count, $conventionsAreConventions, $spec.arithmetic_recomputed.matches_the_record)

$templatesRenderNoLabel = @($surface.explanation_surface.templates | Where-Object { $_.finding_label_rendered -ne $false }).Count -eq 0
Check 'V-R10' 'no finding class is available, both finding labels are forbidden, and no explanation template renders a finding label' `
  ($surface.record_ceiling_carried.finding_classes_available.Count -eq 0 -and ($surface.forbidden_labels -contains 'VIOLATION') -and ($surface.forbidden_labels -contains 'PROBABLE_VIOLATION') -and $templatesRenderNoLabel) `
  ("finding classes available: {0}; forbidden labels: {1}; templates: {2}" -f $surface.record_ceiling_carried.finding_classes_available.Count, $surface.forbidden_labels.Count, $surface.explanation_surface.templates.Count)

$d02 = $determinismDoc.cases | Where-Object { $_.id -eq 'D-02' }
Check 'V-R11' 'the internal determinism check passes every synthetic case, exercises the boundary and the clamp, and emits nothing' `
  ($determinismDoc.failure_count -eq 0 -and $determinismDoc.case_count -ge 20 -and $determinismDoc.emission_tally.cases_that_emitted_a_result -eq 0 -and $determinismDoc.boundary_and_clamp_cases.Count -ge 3 -and $d02.observed.boundary_case -eq 'BOUNDARY_CASE_EXACTLY_AT_SIX_YEAR_ANNIVERSARY' -and $d02.observed.comparison_outcome -eq 'UNRESOLVED') `
  ("cases: {0}; failures: {1}; emitted: {2}; boundary+clamp cases: {3}" -f $determinismDoc.case_count, $determinismDoc.failure_count, $determinismDoc.emission_tally.cases_that_emitted_a_result, $determinismDoc.boundary_and_clamp_cases.Count)

$cmp1 = $comparisonDoc.differences | Where-Object { $_.id -eq 'CMP-1' }
$anyChanged = @($comparisonDoc.differences | Where-Object { $_.implementation_changed_by_this_order -ne $false }).Count
Check 'V-R12' 'the comparison records the material differences, the boundary disagreement among them, and adopts none of them; the implementation is unchanged' `
  ($comparisonDoc.difference_count -ge 5 -and $comparisonDoc.material_differences_not_adopted.Count -ge 3 -and $cmp1.adopted_by_this_specification -eq $false -and $cmp1.implementation_changed_by_this_order -eq $false -and $anyChanged -eq 0) `
  ("differences: {0}; material not adopted: {1}; boundary adopted: {2}; any implementation changed: {3}" -f $comparisonDoc.difference_count, $comparisonDoc.material_differences_not_adopted.Count, $cmp1.adopted_by_this_specification, $anyChanged)

$namedAreNamed = @($verdict.named_not_passed | Where-Object { $_.state -notlike 'NAMED*' }).Count -eq 0
$verdictIsWithheld = $verdict.verdict.StartsWith('WITHHELD')
$acceptanceStates = @($verdict.acceptance_criteria | ForEach-Object { $_.state })
$acceptanceNamed = @($acceptanceStates | Where-Object { $_ -notlike 'MET*' }).Count
$namedUnmet = @($verdict.named_not_passed | Where-Object { $_.state -eq 'NAMED — NOT MET IN THIS SCOPE' }).Count
Check 'V-R13' 'the Gate 5.5 verdict states every criterion with its evidence, names what it cannot meet, withholds itself where a criterion is unmet, and claims no corpus-wide pass' `
  ($verdict.criterion_count -ge 15 -and $verdict.acceptance_criteria_met -ge 5 -and $acceptanceNamed -eq ($verdict.acceptance_criterion_count - $verdict.acceptance_criteria_met) -and $verdict.named_not_passed_count -ge 2 -and $namedAreNamed -and $verdict.corpus_wide_verdict.StartsWith('NOT PASSED') -and (($verdict.verdict -eq 'PASSED_FOR_THIS_SCOPE' -and $namedUnmet -eq 0) -or ($verdictIsWithheld -and $namedUnmet -ge 1))) `
  ("verdict: {0}; criteria: {1}; acceptance met: {2}/{3}; acceptance named: {4}; named items: {5}; named as not met: {6}; corpus-wide starts: {7}" -f $verdict.verdict.Split('—')[0].Trim(), $verdict.criterion_count, $verdict.acceptance_criteria_met, $verdict.acceptance_criterion_count, $acceptanceNamed, $verdict.named_not_passed_count, $namedUnmet, $verdict.corpus_wide_verdict.Substring(0, 10))

$orderIssued = $order.order_issued -eq $true
$draft = if ($orderIssued) { $order } else { $order.the_order_that_would_issue_once_the_blocker_is_cleared }
Check 'V-R14' 'the next step is either an issued Gate 5.6 order for this scope, or the exact remaining blocker with the unissued order kept whole beside it' `
  (($orderIssued -and $order.order_id -eq 'PHASE5-001S' -and $order.issued_for.StartsWith('Gate 5.6') -and $order.type.StartsWith('ISSUED WORK ORDER')) -or ((-not $orderIssued) -and $order.type.StartsWith('NO ORDER ISSUED') -and $order.exact_remaining_blocker.Length -gt 50 -and $order.the_unmet_criteria_that_withhold_it.Count -ge 1 -and $draft.order_id -eq 'PHASE5-001S' -and $draft.deliverables.Count -eq 6 -and $draft.explicit_exclusions.Count -eq 8 -and $draft.stop_conditions.Count -eq 4 -and $draft.acceptance_criteria.Count -eq 7)) `
  ("order issued: {0}; statement: {1}; the draft order for Gate 5.6 is kept whole for whichever branch applies" -f $orderIssued, $order.type)

Check 'V-R22' 'the two records agree on the outcome of Gate 5.5: a withheld verdict for this scope comes with no order issued, and a pass comes with one' `
  (($verdictIsWithheld -and -not $orderIssued) -or (-not $verdictIsWithheld -and $orderIssued)) `
  ("verdict withheld: {0}; order issued: {1}" -f $verdictIsWithheld, $orderIssued)

$recordQ = Get-Content -LiteralPath (Join-Path $Root 'SOURCE_CAPTURES\PHASE5-001Q\rule_record.json') -Raw | ConvertFrom-Json
Check 'V-R15' 'the governed rule record is still NOT ADMITTED, the counts are still zero, and the ceiling is still observation-class only' `
  ($recordQ.admission_state.state -eq 'NOT_ADMITTED' -and $recordQ.admission_state.admitted_governed_rules_after_this_order -eq 0 -and $recordQ.admission_state.permitted_findings_after_this_order -eq 0 -and $recordQ.classification_and_ceiling.permitted_result_ceiling -eq 'OBSERVATION_CLASS_ONLY' -and $surface.record_ceiling_carried.permitted_result_ceiling -eq 'OBSERVATION_CLASS_ONLY') `
  ("state: {0}; rules: {1}; findings: {2}; ceiling: {3}" -f $recordQ.admission_state.state, $recordQ.admission_state.admitted_governed_rules_after_this_order, $recordQ.admission_state.permitted_findings_after_this_order, $recordQ.classification_and_ceiling.permitted_result_ceiling)

# ---------------------------------------------------------------- the PHASE5-001Q package and the implementation are unchanged
$supersededPaths = @($inputs.superseded_self_measurements_explained | ForEach-Object { $_.path })
$qPackageChecked = @($inputs.rows | Where-Object { $_.path -like 'SOURCE_CAPTURES\PHASE5-001Q\*' -and $_.recorded_sha256 -and ($supersededPaths -notcontains $_.path) }).Count
$qPackageRows = @($inputs.rows | Where-Object { $_.path -like 'SOURCE_CAPTURES\PHASE5-001Q\*' -and ($supersededPaths -notcontains $_.path) -and $_.state -eq 'MATCHES_RECORDED_DIGEST' }).Count
Check 'V-R16' 'every artifact of the PHASE5-001Q package it builds on still measures to the digest that order recorded' `
  ($qPackageChecked -ge 10 -and $qPackageRows -eq $qPackageChecked) `
  ("Q artifacts with a recorded digest, excluding that order's three superseded self-measurements: {0}; matching: {1}; superseded and reconciled: {2}" -f $qPackageChecked, $qPackageRows, $supersededPaths.Count)

$implRows = @($inputs.rows | Where-Object { $_.path -like 'internal-validation\*' })
$implChecked = @($implRows | Where-Object { $_.recorded_sha256 }).Count
$implMatching = @($implRows | Where-Object { $_.state -eq 'MATCHES_RECORDED_DIGEST' }).Count
Check 'V-R17' 'the internal comparator is at the digest the comparison cites, and no implementation file was changed' `
  ($implRows.Count -ge 12 -and $implMatching -eq $implChecked -and $inputs.unexplained_differences.Count -eq 0) `
  ("implementation files measured: {0}; with a recorded digest: {1}; matching: {2}; unexplained input differences: {3}" -f $implRows.Count, $implChecked, $implMatching, $inputs.unexplained_differences.Count)

$comparisonImplMismatch = 0
foreach ($e in $comparisonDoc.the_implementation_at_its_digests) {
  $row = $inputs.rows | Where-Object { $_.path -eq $e.file }
  if (-not $row -or $row.sha256 -ne $e.sha256) { $comparisonImplMismatch++ }
}
Check 'V-R21' 'the implementation digests the comparison cites are the digests the input record measured, and the comparison states it did not re-run the writing suite' `
  ($comparisonImplMismatch -eq 0 -and $comparisonDoc.its_own_test_suite.re_run_by_this_order -eq $false -and $comparisonDoc.its_own_test_suite.failures -eq 0 -and $disclosedPaths.Count -eq 1) `
  ("digest disagreements between the comparison and the input record: {0}; suite re-run by this order: {1}; disclosed changes: {2}" -f $comparisonImplMismatch, $comparisonDoc.its_own_test_suite.re_run_by_this_order, $disclosedPaths.Count)


# ---------------------------------------------------------------- the read-only pointers outside the workspace
$record = Get-Content -LiteralPath (Join-Path $Root 'SOURCE_CAPTURES\PHASE5-001Q\rule_record.json') -Raw | ConvertFrom-Json
$register = Get-Content -LiteralPath (Join-Path $Root 'SOURCE_CAPTURES\PROD-003\report_representation_register.json') -Raw | ConvertFrom-Json
$pr01 = $register.presentations | Where-Object { $_.presentation_id -eq 'PR-01' }
$pr02 = $register.presentations | Where-Object { $_.presentation_id -eq 'PR-02' }
$readOnly = New-Object System.Collections.Generic.List[object]
$pointerMismatch = 0
$pointerTable = @(
  [pscustomobject]@{ label = 'the admitted source pin (accepted legal authority)'; rel = $SourcePin; recorded = $record.legal_proposition.source_pin.sha256; recorded_bytes = $record.legal_proposition.source_pin.bytes },
  [pscustomobject]@{ label = 'consumer specimen PR-01 (the scope''s byte-pinned presentation)'; rel = $SpecimenPrimary; recorded = $pr01.sha256; recorded_bytes = $pr01.bytes },
  [pscustomobject]@{ label = 'consumer specimen PR-02 (secondary, admitted for no rule unit)'; rel = $SpecimenSecondary; recorded = $pr02.sha256; recorded_bytes = $pr02.bytes }
)
foreach ($p in $pointerTable) {
  $abs = Join-Path $Legacy $p.rel
  $exists = Test-Path -LiteralPath $abs -PathType Leaf
  $bytes = $null; $sha = $null; $state = 'MISSING'
  if ($exists) {
    $bytes = (Get-Item -LiteralPath $abs).Length
    $sha = Get-Sha256 $abs
    if ($sha -eq $p.recorded.ToUpperInvariant() -and $bytes -eq $p.recorded_bytes) { $state = 'MATCHES_THE_RECORDED_PIN' } else { $state = 'DIFFERS_FROM_THE_RECORDED_PIN'; $pointerMismatch++ }
  } else { $pointerMismatch++ }
  $readOnly.Add([pscustomobject][ordered]@{ label = $p.label; path = (Join-Path $Legacy $p.rel); bytes = $bytes; sha256 = $sha; recorded_sha256 = $p.recorded.ToUpperInvariant(); recorded_bytes = $p.recorded_bytes; state = $state })
}
Check 'V-R18' 'the three read-only pointers outside the workspace still measure to the digests the records pin' ($pointerMismatch -eq 0) ("mismatching pointers: {0}; measured read-only, in place; nothing copied, moved, renamed, written or transmitted" -f $pointerMismatch)

# ---------------------------------------------------------------- preservation and change record
[ordered]@{
  artifact              = 'preservation_and_change_record.json'
  work_order            = 'PHASE5-001R'
  created_utc           = '2026-09-30'
  baseline_artifact     = 'preserved_files_before.json'
  baseline_files        = $baseline.file_count
  files_unchanged       = $unchanged
  files_changed         = $changed.ToArray()
  files_missing         = $missing.ToArray()
  files_added_by_this_order = $addedByThisOrder.ToArray()
  expected_changes      = 'none. This order was authorised to change no pre-existing file. One was changed, and it is disclosed below rather than absorbed: the PHASE5-001I-A internal test suite writes its results into its own package when it is run, and this order ran it once before that was established. The run was removed from every builder of this order, and the file is measured stable across builder runs from that point on.'
  disclosed_changes_by_this_order = $disclosedChanges
  disclosed_change_count = $disclosedChanges.Count
  undeclared_changes    = @($undeclaredChanges)
  legal_corpus_untouched = $true
  legacy_corpus_files_written_or_deleted = 0
  governed_documents_amended = @()
  output_character      = 'observation-only, packet-ineligible: no consumer-visible output, no application change, no deployment'
  verdict               = if ($undeclaredChanges.Count -eq 0 -and $missing.Count -eq 0) { 'PRESERVATION NOT FULLY HELD — no pre-existing file was deleted, and no pre-existing file was changed outside the one change this order discloses and does not authorise' } else { 'CHECK — unexpected preservation reading' }
} | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $Out 'preservation_and_change_record.json') -Encoding utf8

# ---------------------------------------------------------------- custody manifest
$harnessSummaryRecords = @('preservation_and_change_record.json', 'file_custody_manifest.json', 'verification_results.json')
$manifestFiles = New-Object System.Collections.Generic.List[object]
foreach ($e in $addedByThisOrder) {
  if ($harnessSummaryRecords -contains [System.IO.Path]::GetFileName($e.relative_path)) { continue }
  $abs = Join-Path $Root $e.relative_path
  $manifestFiles.Add([pscustomobject][ordered]@{ relative_path_from_workspace = $e.relative_path; bytes = (Get-Item -LiteralPath $abs).Length; sha256 = Get-Sha256 $abs })
}
foreach ($e in $baseline.files) {
  if ($disclosedPaths -contains $e.relative_path) {
    $abs = Join-Path $Root $e.relative_path
    $manifestFiles.Add([pscustomobject][ordered]@{
      relative_path_from_workspace = $e.relative_path
      bytes                        = (Get-Item -LiteralPath $abs).Length
      sha256                       = Get-Sha256 $abs
      baseline_sha256              = $e.sha256
      disclosed_change_by_this_order = 'YES — this file was changed by this order and the change is disclosed in preservation_and_change_record.json and verification_results.json. It is not authorised by this order.'
    })
    continue
  }
  $manifestFiles.Add([pscustomobject][ordered]@{ relative_path_from_workspace = $e.relative_path; bytes = $e.bytes; sha256 = $e.sha256 })
}
[ordered]@{
  artifact         = 'file_custody_manifest.json'
  work_order       = 'PHASE5-001R'
  created_utc      = '2026-09-30'
  purpose          = 'record, in one place, the digest of every file this order read or wrote, so custody is measured rather than asserted'
  file_count       = $manifestFiles.Count
  files            = $manifestFiles.ToArray()
  harness_summary_records_excluded_from_files = [pscustomobject][ordered]@{
    records = $harnessSummaryRecords
    why     = 'these three records are written by this same harness during the run, so a digest recorded inside one of them for itself or for another would be stale by construction. They are listed in added_by_this_order and their final digests are recorded in verification_results.json; every pre-existing file is proved preserved by the baseline comparison instead.'
  }
  added_by_this_order = $addedByThisOrder.ToArray()
  read_only_outside_the_workspace = $readOnly.ToArray()
  plan_digest      = [pscustomobject][ordered]@{
    path            = $Plan
    sha256          = Get-Sha256 (Join-Path $Root $Plan)
    baseline_sha256 = $baselineByPath[$Plan].sha256
    state           = 'UNCHANGED_BY_THIS_ORDER — the build plan is the rank-5 instrument this order reads, and it is byte-identical to the baseline taken before this order wrote anything'
  }
  preservation_reading = [pscustomobject][ordered]@{
    baseline_files            = $baseline.file_count
    files_unchanged           = $unchanged
    files_changed             = $changed.Count
    files_missing             = $missing.Count
    files_added_by_this_order = $addedByThisOrder.Count
  }
  created_by = 'PHASE5-001R'
} | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $Out 'file_custody_manifest.json') -Encoding utf8

# ---------------------------------------------------------------- results
$manifestBack = Get-Content -LiteralPath (Join-Path $Out 'file_custody_manifest.json') -Raw | ConvertFrom-Json
$manifestMismatch = 0
foreach ($e in $manifestBack.files) { if ((Get-Sha256 (Join-Path $Root $e.relative_path_from_workspace)) -ne $e.sha256) { $manifestMismatch++ } }
Check 'V-R19' 'the custody manifest re-measures with no mismatch over the files it lists' ($manifestMismatch -eq 0) ("entries: {0}; mismatching: {1}. The three harness summary records are listed separately in the manifest and excluded from its files list, because a record cannot carry its own final digest" -f $manifestBack.file_count, $manifestMismatch)
$failures = @($checks | Where-Object { $_.passed -ne $true })

[ordered]@{
  artifact      = 'verification_results.json'
  work_order    = 'PHASE5-001R'
  created_utc   = '2026-09-30'
  purpose       = 'the checks this order ran over its own artifacts, its builders, its preservation, its custody, the artifacts it builds on and the read-only pointers outside the workspace'
  checks        = $checks.ToArray()
  check_count   = $checks.Count
  failure_count = $failures.Count
  failed        = $failures
  verdict       = if ($failures.Count -eq 0) { 'ALL PHASE5-001R CHECKS PASSED' } else { 'CHECK FAILURES PRESENT' }
  checks_are_not_gate_evidence = 'these checks verify this order''s own artifacts and custody. They are not the scope''s gate verdict, which is a separate record: scoped_gate_5_5_verdict.json.'
  disclosed_changes_by_this_order = $disclosedChanges
  disclosed_change_count = $disclosedChanges.Count
  undeclared_changes = @($undeclaredChanges)
  preservation_reading = 'one pre-existing file was changed, by this order, and it is disclosed: SOURCE_CAPTURES\PHASE5-001I-A\test_results_001i_a.json. The cause was removed from this order''s builders, and no other pre-existing file was changed or deleted.'
  artifacts_this_order_wrote = $addedByThisOrder.ToArray()
  harness_summary_records = @(
    [pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001R\preservation_and_change_record.json'; bytes = (Get-Item -LiteralPath (Join-Path $Out 'preservation_and_change_record.json')).Length; sha256 = Get-Sha256 (Join-Path $Out 'preservation_and_change_record.json') },
    [pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001R\file_custody_manifest.json'; bytes = (Get-Item -LiteralPath (Join-Path $Out 'file_custody_manifest.json')).Length; sha256 = Get-Sha256 (Join-Path $Out 'file_custody_manifest.json') },
    [pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001R\verification_results.json'; note = 'written last by this same harness; its own digest is measured from the file rather than self-recorded' }
  )
  builders_and_their_artifacts = $regeneration.ToArray()
  corpus_wide_status_kept_separate = [pscustomobject][ordered]@{
    '5.1' = 'MET with recorded administrative limitations; unchanged'
    '5.2' = 'NOT PASSED corpus-wide; a scoped verdict is recorded separately'
    '5.3' = 'NOT PASSED corpus-wide; a scoped verdict is recorded separately'
    '5.4' = 'NOT PASSED corpus-wide; PASSED_FOR_THIS_SCOPE only, in SOURCE_CAPTURES\PHASE5-001Q\scoped_gate_5_4_verdict.json'
    '5.5' = 'NOT PASSED corpus-wide; the scoped verdict for this scope is WITHHELD, with the unmet criterion named in SOURCE_CAPTURES\PHASE5-001R\scoped_gate_5_5_verdict.json'
    '5.6' = 'NOT STARTED; no order issued — the remaining blocker is recorded in SOURCE_CAPTURES\PHASE5-001R\next_work_order.json, with the unissued Gate 5.6 order kept beside it'
    '5.7' = 'NOT REACHED; 0 admitted governed rules, 0 permitted findings'
  }
  what_this_record_does_not_claim = @(
    'it is not independent legal review, and it is not Gate 5.6 or Gate 5.7 evidence',
    'it does not pass Gate 5.5 corpus-wide, and it records no gate as passed for any scope other than the one named in scoped_gate_5_5_verdict.json',
    'it does not admit a rule, create coverage or a candidate, or authorize a finding class',
    'it does not convert any recorded limitation into a criterion satisfaction, and it does not treat missing work as GAP or REFUSAL',
    'it does not present the one change it made to a pre-existing file as authorised, or as no change: the change is disclosed by measurement, with its cause, and the acceptance criterion it affects is named as unmet in scoped_gate_5_5_verdict.json',
    'it does not retroactively authorize the custody discrepancies that earlier orders recorded'
  )
  created_by    = 'PHASE5-001R'
} | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $Out 'verification_results.json') -Encoding utf8

"checks: {0} | failures: {1} | changed: {2} | missing: {3} | added by this order: {4}" -f $checks.Count, $failures.Count, $changed.Count, $missing.Count, $addedByThisOrder.Count
foreach ($f in $failures) { "  FAIL {0}: {1} :: {2}" -f $f.id, $f.what, $f.detail }





