'use strict';
/**
 * tests/harness.cjs — the small test harness and the shared context for the PHASE5-001I-A suite.
 *
 * The suite is split into section modules so that every file is written whole and no part of the suite is
 * ever spliced. Each section exports `run(ctx)` and registers its tests through `ctx.test`.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const constants = require('../constants.cjs');
const { buildPdfDocumentModel, makeSyntheticModel, readPinnedPresentationPointer } = require('../document-model.cjs');
const { admitDocument } = require('../presentation-contract.cjs');
const { extractFacts } = require('../extraction.cjs');
const { evaluateModel, checkSelection } = require('../run-internal-validation.cjs');
const { evaluateSixYearPeriod, addCalendarYears, daysBetween } = require('../six-year-evaluator.cjs');
const fixtures = require('./fixtures.cjs');

const OUT = path.join('C:\\CRP-NEW', 'SOURCE_CAPTURES', 'PHASE5-001I-A');
const results = [];
let failures = 0;

function test(name, fn) {
  try {
    const detail = fn();
    results.push({ test: name, passed: true, detail: detail === undefined ? '' : String(detail) });
  } catch (err) {
    failures += 1;
    results.push({ test: name, passed: false, detail: err.message });
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
  return message;
}

function canonical(value) {
  if (Array.isArray(value)) return '[' + value.map(canonical).join(',') + ']';
  if (value && typeof value === 'object') {
    return '{' + Object.keys(value).sort().map((k) => JSON.stringify(k) + ':' + canonical(value[k])).join(',') + '}';
  }
  return JSON.stringify(value);
}

const EVIDENCE = readPinnedPresentationPointer();
const SELECTION = {
  country_code: 'CA', region_code: 'CA-NS', explicit_selection_supplied: true,
  authorized_for_this_unit: true, enumerated_region_found: true, verdict: 'AUTHORIZED',
  enumerated_in: 'CRP_JURISDICTION_ENUMERATION.md (CRP-JURISDICTION-ENUM-1)',
  jurisdiction_is_never_inferred_from_the_report: true
};
const MODEL = buildPdfDocumentModel(EVIDENCE.absolute_path);

const ctx = {
  constants, fixtures, test, assert, canonical, EVIDENCE, SELECTION, MODEL,
  buildPdfDocumentModel, makeSyntheticModel, admitDocument, extractFacts, evaluateModel, checkSelection,
  evaluateSixYearPeriod, addCalendarYears, daysBetween,
  pinnedRun: () => evaluateModel(MODEL, SELECTION, EVIDENCE, 'the pinned specimen'),
  syntheticRun: (model) => evaluateModel(model, SELECTION, null, 'synthetic test input', { synthetic_test_input: true })
};

/** Write the results record and return the process exit code. */
function finish() {
  const fixtureFiles = fs.existsSync(fixtures.FIXTURE_DIR)
    ? fs.readdirSync(fixtures.FIXTURE_DIR).sort().map((name) => {
      const file = path.join(fixtures.FIXTURE_DIR, name);
      return {
        name, bytes: fs.statSync(file).size,
        sha256: crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex').toUpperCase()
      };
    })
    : [];

  const summary = {
    artifact: 'test_results_001i_a.json',
    work_order: 'PHASE5-001I-A',
    created_utc: new Date().toISOString().slice(0, 10),
    purpose: 'the unit\'s suite: the pinned presentation end to end, the six-year arithmetic, the failure and ambiguity paths, the refusal paths and the state model',
    subject: {
      unit_id: 'CA-NS-CRA-S10-3-C-LIMB-1',
      presentation_id: 'PR-01',
      evidenced_artifact_id: EVIDENCE.artifact_id,
      evidenced_sha256: EVIDENCE.sha256,
      specimen_path_policy: 'read from the path recorded by PROD-003\'s register; no path and no identifier is copied into this package'
    },
    synthetic_fixture_directory: fixtures.FIXTURE_DIR,
    synthetic_fixture_files: fixtureFiles,
    synthetic_fixture_note: 'every fixture is generated by this order for test input, carries a synthetic marker, and is never presentation evidence',
    test_count: results.length,
    failures,
    tests: results,
    verdict: failures === 0 ? 'ALL PHASE5-001I-A TESTS PASSED' : 'TESTS FAILED — see failures'
  };

  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, 'test_results_001i_a.json'), JSON.stringify(summary, null, 2) + '\n', 'utf8');
  for (const r of results) console.log(`${r.passed ? 'PASS' : 'FAIL'}  ${r.test} — ${r.detail}`);
  console.log(`${results.length} tests, ${failures} failures`);
  console.log(summary.verdict);
  return failures === 0 ? 0 : 1;
}

module.exports = { ctx, finish };
