# verify_and_manifest_001q.ps1 — PHASE5-001Q: verification, preservation and custody.
#
# Measures rather than asserts. It re-takes every digest, re-parses every JSON artifact this order wrote,
# re-runs every builder and compares the regenerated bytes with the bytes on disk (so a hand-edited artifact
# and a non-deterministic builder are both caught), compares the whole workspace against the baseline taken
# before this order wrote anything, and re-measures the read-only legacy pointers: the admitted source pin
# and the two consumer specimens.
# It writes preservation_and_change_record.json, file_custody_manifest.json and verification_results.json.

$ErrorActionPreference = 'Stop'
$Root = 'C:\CRP-NEW'
$Out = Join-Path $Root 'SOURCE_CAPTURES\PHASE5-001Q'
$Legacy = 'C:\Users\webbd\crp-credit-app'
$Plan = 'CRP_PHASE5_STATUTE_CERTIFICATION_AND_FINDING_AUTHORIZATION_BUILD_PLAN.md'
$Narrative = 'CRP_PHASE5_001Q_RULE_RECORD_FINALIZATION_AND_GATE_5_4_VERDICT.md'
$SourcePin = 'packages\backend\src\services\legalCorpus\rules.canada.ts'
$SpecimenPrimary = 'packages\backend\fixtures\reports\equifax-david-webb.pdf'
$SpecimenSecondary = 'packages\backend\fixtures\reports\transunion-david-webb.pdf'

function Get-Sha256([string]$path) { return (Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash }
function Rel([string]$path) { return $path.Substring($Root.Length + 1) }

$checks = New-Object System.Collections.Generic.List[object]
function Check([string]$id, [string]$what, [bool]$passed, [string]$detail) {
  $checks.Add([pscustomobject][ordered]@{ id = $id; what = $what; passed = $passed; detail = $detail })
}

$baseline = Get-Content -LiteralPath (Join-Path $Out 'preserved_files_before.json') -Raw | ConvertFrom-Json
$baselineByPath = @{}
foreach ($f in $baseline.files) { $baselineByPath[$f.relative_path] = $f }

# ---------------------------------------------------------------- preservation (measured)
$changed = New-Object System.Collections.Generic.List[object]
$missing = New-Object System.Collections.Generic.List[string]
$unchanged = 0
foreach ($f in $baseline.files) {
  $abs = Join-Path $Root $f.relative_path
  if (-not (Test-Path -LiteralPath $abs -PathType Leaf)) { $missing.Add($f.relative_path); continue }
  $now = Get-Sha256 $abs
  if ($now -eq $f.sha256) { $unchanged++ } else {
    $changed.Add([pscustomobject][ordered]@{ relative_path = $f.relative_path; before = $f.sha256; after = $now; bytes = (Get-Item -LiteralPath $abs).Length })
  }
}

# ---------------------------------------------------------------- files added by this order
$addedByThisOrder = New-Object System.Collections.Generic.List[object]
foreach ($f in (Get-ChildItem -LiteralPath $Out -File | Sort-Object Name)) {
  $addedByThisOrder.Add([pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001Q\' + $f.Name; bytes = $f.Length; sha256 = Get-Sha256 $f.FullName })
}
$narrativeAbs = Join-Path $Root $Narrative
$narrativeExists = Test-Path -LiteralPath $narrativeAbs -PathType Leaf
if ($narrativeExists) {
  $addedByThisOrder.Add([pscustomobject][ordered]@{ relative_path = $Narrative; bytes = (Get-Item -LiteralPath $narrativeAbs).Length; sha256 = Get-Sha256 $narrativeAbs })
}

Check 'V-Q1' 'no pre-existing file was changed by this order' ($changed.Count -eq 0) ("changed: {0}" -f $changed.Count)
Check 'V-Q2' 'no pre-existing file was deleted by this order' ($missing.Count -eq 0) ("missing: {0}" -f $missing.Count)


# ---------------------------------------------------------------- every artifact this order wrote parses, and no BOM
$jsonArtifacts = @('rule_record.json', 'rule_record_decisions.json', 'transcription_mapping_validation.json', 'scoped_gate_5_4_verdict.json', 'next_work_order.json', 'input_verification.json', 'preserved_files_before.json')
$badJson = New-Object System.Collections.Generic.List[string]
$bomFound = New-Object System.Collections.Generic.List[string]
$parsed = @{}
foreach ($name in $jsonArtifacts) {
  $abs = Join-Path $Out $name
  if (-not (Test-Path -LiteralPath $abs -PathType Leaf)) { $badJson.Add($name + ' (absent)'); continue }
  $bytes = [System.IO.File]::ReadAllBytes($abs)
  if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) { $bomFound.Add($name) }
  try { $parsed[$name] = Get-Content -LiteralPath $abs -Raw | ConvertFrom-Json } catch { $badJson.Add($name + ' (' + $_.Exception.Message + ')') }
}
Check 'V-Q3' 'every JSON artifact of this order parses' ($badJson.Count -eq 0) ("unparsable: {0}" -f ($badJson -join ', '))
Check 'V-Q4' 'no artifact of this order carries a byte-order mark' ($bomFound.Count -eq 0) ("with BOM: {0}" -f ($bomFound -join ', '))
Check 'V-Q5' 'the narrative record exists' $narrativeExists $Narrative

# ---------------------------------------------------------------- the builders regenerate the same bytes
$builders = @('build_001q_rule_record.js', 'build_001q_decisions.js', 'build_001q_validation.js', 'build_001q_gate54.js', 'build_001q_next_order.js')
$producedBy = @{ 'build_001q_rule_record.js' = 'rule_record.json'; 'build_001q_decisions.js' = 'rule_record_decisions.json'; 'build_001q_validation.js' = 'transcription_mapping_validation.json'; 'build_001q_gate54.js' = 'scoped_gate_5_4_verdict.json'; 'build_001q_next_order.js' = 'next_work_order.json' }
$regeneration = New-Object System.Collections.Generic.List[object]
$regression = 0
foreach ($b in $builders) {
  $target = Join-Path $Out $producedBy[$b]
  $before = Get-Sha256 $target
  Push-Location $Root
  $null = & node (Join-Path $Out $b) 2>&1
  $exit = $LASTEXITCODE
  Pop-Location
  $after = Get-Sha256 $target
  $identical = ($before -eq $after)
  if (-not $identical -or $exit -ne 0) { $regression++ }
  $regeneration.Add([pscustomobject][ordered]@{ builder = $b; exit_code = $exit; artifact = $producedBy[$b]; sha256_before = $before; sha256_after = $after; byte_identical = $identical })
}
Check 'V-Q6' 'every builder re-runs cleanly and regenerates its artifact byte-for-byte, so no artifact was hand-edited' ($regression -eq 0) ("builders with a difference or a non-zero exit: {0}" -f $regression)

# ---------------------------------------------------------------- content checks on the artifacts themselves
$record = $parsed['rule_record.json']
$decisions = $parsed['rule_record_decisions.json']
$validation = $parsed['transcription_mapping_validation.json']
$verdict54 = $parsed['scoped_gate_5_4_verdict.json']
$order = $parsed['next_work_order.json']

Check 'V-Q7' 'the rule record carries the 13 required governed fields and asserts no admission' ($record.governed_fields.Count -eq 13 -and $record.admission_state.state -eq 'NOT_ADMITTED' -and $record.admission_state.governed_rule_created -eq $false) ("fields: {0}; state: {1}" -f $record.governed_fields.Count, $record.admission_state.state)
Check 'V-Q8' 'the decisions record holds exactly six decisions, one per item the issuing order names' ($decisions.decisions.Count -eq 6 -and $decisions.decision_outcome_summary.decisions_that_failed_their_gate_5_4_criterion.Count -eq 0) ("decisions: {0}" -f $decisions.decisions.Count)
Check 'V-Q9' 'the validation record holds its checks with no failure' ($validation.failure_count -eq 0 -and $validation.check_count -ge 20) ("checks: {0}; failures: {1}" -f $validation.check_count, $validation.failure_count)
Check 'V-Q10' 'the scoped Gate 5.4 verdict is issued for this scope only, with no unmet criterion' ($verdict54.verdict -eq 'PASSED_FOR_THIS_SCOPE' -and $verdict54.criterion_count -ge 10 -and ($verdict54.unmet_criteria_named -is [string])) ("verdict: {0}; criteria: {1}" -f $verdict54.verdict, $verdict54.criterion_count)
Check 'V-Q11' 'the Gate 5.4 verdict does not claim a corpus-wide pass' ($verdict54.corpus_wide_verdict.StartsWith('NOT PASSED')) ("corpus-wide: {0}" -f $verdict54.corpus_wide_verdict.Substring(0, 40))
Check 'V-Q12' 'the issued order is the Gate 5.5 order for this scope and was not executed' ($order.issued_for.StartsWith('Gate 5.5') -and $order.order_id -eq 'PHASE5-001R' -and $order.type.StartsWith('ISSUED WORK ORDER')) ("order: {0} — {1}" -f $order.order_id, $order.issued_for)
Check 'V-Q13' 'the rule record points at the decisions, validation, verdict and order records as files in this package' ((Test-Path -LiteralPath (Join-Path $Root $record.decisions_record) -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $Root $record.validation_record) -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $Root $record.scope_gate_5_4_verdict_record) -PathType Leaf) -and (Test-Path -LiteralPath (Join-Path $Root ($record.next_work_order_issued.Split(' ')[0])) -PathType Leaf)) 'the four pointers resolve to files that exist'

# ---------------------------------------------------------------- the read-only pointers outside the workspace
$register = Get-Content -LiteralPath (Join-Path $Root 'SOURCE_CAPTURES\PROD-003\report_representation_register.json') -Raw | ConvertFrom-Json
$pr01 = $register.presentations | Where-Object { $_.presentation_id -eq 'PR-01' }
$pr02 = $register.presentations | Where-Object { $_.presentation_id -eq 'PR-02' }
$readOnly = New-Object System.Collections.Generic.List[object]
$pointerMismatch = 0
$pointerTable = @(
  [pscustomobject]@{ label = 'the admitted source pin (accepted legal authority)'; rel = $SourcePin; recorded = $record.legal_proposition.source_pin.sha256; recorded_bytes = $record.legal_proposition.source_pin.bytes },
  [pscustomobject]@{ label = 'consumer specimen PR-01 (the scope''s byte-pinned presentation)'; rel = $SpecimenPrimary; recorded = $pr01.sha256; recorded_bytes = $pr01.bytes },
  [pscustomobject]@{ label = 'consumer specimen PR-02 (secondary, not admitted for any rule unit)'; rel = $SpecimenSecondary; recorded = $pr02.sha256; recorded_bytes = $pr02.bytes }
)
foreach ($p in $pointerTable) {
  $abs = Join-Path $Legacy $p.rel
  $exists = Test-Path -LiteralPath $abs -PathType Leaf
  $bytes = $null; $sha = $null; $state = 'MISSING'
  if ($exists) {
    $bytes = (Get-Item -LiteralPath $abs).Length
    $sha = Get-Sha256 $abs
    if ($sha -eq $p.recorded.ToUpperInvariant() -and $bytes -eq $p.recorded_bytes) { $state = 'MATCHES_THE_RECORDED_PIN' } else { $state = 'DIFFERS_FROM_THE_RECORDED_PIN'; $pointerMismatch++ }
  } else { $pointerMismatch++ }
  $readOnly.Add([pscustomobject][ordered]@{ label = $p.label; path = (Join-Path $Legacy $p.rel); bytes = $bytes; sha256 = $sha; recorded_sha256 = $p.recorded.ToUpperInvariant(); recorded_bytes = $p.recorded_bytes; state = $state })
}
Check 'V-Q14' 'the three read-only pointers outside the workspace still measure to the digests the records pin' ($pointerMismatch -eq 0) ("mismatching pointers: {0}; measured read-only, in place; nothing copied, moved, renamed, written or transmitted" -f $pointerMismatch)

# ---------------------------------------------------------------- preservation and change record
[ordered]@{
  artifact              = 'preservation_and_change_record.json'
  work_order            = 'PHASE5-001Q'
  created_utc           = '2026-09-30'
  baseline_artifact     = 'preserved_files_before.json'
  baseline_files        = $baseline.file_count
  files_unchanged       = $unchanged
  files_changed         = $changed.ToArray()
  files_missing         = $missing.ToArray()
  files_added_by_this_order = $addedByThisOrder.ToArray()
  expected_changes      = 'none. This order was authorised to change no pre-existing file; every file it wrote is new and lives in its own package or is its own narrative.'
  legal_corpus_untouched = $true
  legacy_corpus_files_written_or_deleted = 0
  governed_documents_amended = @()
  output_character      = 'observation-only, packet-ineligible: no consumer-visible output, no application change, no deployment'
  verdict               = if ($changed.Count -eq 0 -and $missing.Count -eq 0) { 'PRESERVATION HELD — no pre-existing file was changed or deleted by this order; every artifact it wrote is new' } else { 'CHECK — unexpected preservation reading' }
} | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $Out 'preservation_and_change_record.json') -Encoding utf8

# ---------------------------------------------------------------- custody manifest
$harnessSummaryRecords = @('preservation_and_change_record.json', 'file_custody_manifest.json', 'verification_results.json')
$manifestFiles = New-Object System.Collections.Generic.List[object]
foreach ($e in $addedByThisOrder) {
  if ($harnessSummaryRecords -contains [System.IO.Path]::GetFileName($e.relative_path)) { continue }
  $abs = Join-Path $Root $e.relative_path
  $manifestFiles.Add([pscustomobject][ordered]@{ relative_path_from_workspace = $e.relative_path; bytes = (Get-Item -LiteralPath $abs).Length; sha256 = Get-Sha256 $abs })
}
foreach ($e in $baseline.files) {
  $manifestFiles.Add([pscustomobject][ordered]@{ relative_path_from_workspace = $e.relative_path; bytes = $e.bytes; sha256 = $e.sha256 })
}
[ordered]@{
  artifact         = 'file_custody_manifest.json'
  work_order       = 'PHASE5-001Q'
  created_utc      = '2026-09-30'
  purpose          = 'record, in one place, the digest of every file this order read or wrote, so custody is measured rather than asserted'
  file_count       = $manifestFiles.Count
  files            = $manifestFiles.ToArray()
  harness_summary_records_excluded_from_files = [pscustomobject][ordered]@{
    records = $harnessSummaryRecords
    why     = 'these three records are written by this same harness during the run, so a digest recorded inside one of them for itself or for another would be stale by construction. They are listed in added_by_this_order and their final digests are recorded in verification_results.json; every pre-existing file is proved preserved by the baseline comparison instead.'
  }
  added_by_this_order = $addedByThisOrder.ToArray()
  read_only_outside_the_workspace = $readOnly.ToArray()
  plan_digest      = [pscustomobject][ordered]@{
    path         = $Plan
    sha256       = Get-Sha256 (Join-Path $Root $Plan)
    baseline_sha256 = $baselineByPath[$Plan].sha256
    state        = 'UNCHANGED_BY_THIS_ORDER — the build plan is the rank-5 instrument this order reads, and it is byte-identical to the baseline taken before this order wrote anything'
  }
  preservation_reading = [pscustomobject][ordered]@{
    baseline_files            = $baseline.file_count
    files_unchanged           = $unchanged
    files_changed             = $changed.Count
    files_missing             = $missing.Count
    files_added_by_this_order = $addedByThisOrder.Count
  }
  created_by = 'PHASE5-001Q'
} | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $Out 'file_custody_manifest.json') -Encoding utf8


# ---------------------------------------------------------------- results
$manifestBack = Get-Content -LiteralPath (Join-Path $Out 'file_custody_manifest.json') -Raw | ConvertFrom-Json
$manifestMismatch = 0
foreach ($e in $manifestBack.files) { if ((Get-Sha256 (Join-Path $Root $e.relative_path_from_workspace)) -ne $e.sha256) { $manifestMismatch++ } }
Check 'V-Q15' 'the custody manifest re-measures with no mismatch over the files it lists' ($manifestMismatch -eq 0) ("entries: {0}; mismatching: {1}. The three harness summary records are listed separately in the manifest and excluded from its files list, because a record cannot carry its own final digest" -f $manifestBack.file_count, $manifestMismatch)
$failures = @($checks | Where-Object { $_.passed -ne $true })

[ordered]@{
  artifact      = 'verification_results.json'
  work_order    = 'PHASE5-001Q'
  created_utc   = '2026-09-30'
  purpose       = 'the checks this order ran over its own artifacts, its builders, its preservation, its custody and the read-only pointers outside the workspace'
  checks        = $checks.ToArray()
  check_count   = $checks.Count
  failure_count = $failures.Count
  failed        = $failures
  verdict       = if ($failures.Count -eq 0) { 'ALL PHASE5-001Q CHECKS PASSED' } else { 'CHECK FAILURES PRESENT' }
  validation_is_separate = 'the independent validation of transcription and mapping is a separate artifact, transcription_mapping_validation.json, written by build_001q_validation.js. These checks are not that validation and are not gate evidence.'
  artifacts_this_order_wrote = $addedByThisOrder.ToArray()
  harness_summary_records = @(
    [pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001Q\preservation_and_change_record.json'; bytes = (Get-Item -LiteralPath (Join-Path $Out 'preservation_and_change_record.json')).Length; sha256 = Get-Sha256 (Join-Path $Out 'preservation_and_change_record.json') },
    [pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001Q\file_custody_manifest.json'; bytes = (Get-Item -LiteralPath (Join-Path $Out 'file_custody_manifest.json')).Length; sha256 = Get-Sha256 (Join-Path $Out 'file_custody_manifest.json') },
    [pscustomobject][ordered]@{ relative_path = 'SOURCE_CAPTURES\PHASE5-001Q\verification_results.json'; note = 'written last by this same harness; its own digest is measured from the file rather than self-recorded' }
  )
  builders_and_their_artifacts = $regeneration.ToArray()
  corpus_wide_status_kept_separate = [pscustomobject][ordered]@{
    '5.1' = 'MET with recorded administrative limitations; unchanged'
    '5.2' = 'NOT PASSED corpus-wide; a scoped verdict is recorded separately'
    '5.3' = 'NOT PASSED corpus-wide; a scoped verdict is recorded separately'
    '5.4' = 'NOT PASSED corpus-wide; PASSED_FOR_THIS_SCOPE only, recorded in scoped_gate_5_4_verdict.json'
    '5.5' = 'NOT STARTED; issued as PHASE5-001R for this scope only, not executed'
    '5.6' = 'NOT STARTED'
    '5.7' = 'NOT REACHED; 0 admitted governed rules, 0 permitted findings'
  }
  what_this_record_does_not_claim = @(
    'it is not independent legal review and is not Gate 5.5 or Gate 5.6 evidence',
    'it does not pass Gate 5.4 corpus-wide, and it records no gate as passed for any scope other than the one named in scoped_gate_5_4_verdict.json',
    'it does not admit a rule, create coverage or a candidate, or authorize a finding class',
    'it does not convert any recorded limitation into a criterion satisfaction, and it does not treat missing work as GAP or REFUSAL',
    'it does not retroactively authorize the custody discrepancies that earlier orders recorded'
  )
  created_by    = 'PHASE5-001Q'
} | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath (Join-Path $Out 'verification_results.json') -Encoding utf8

"checks: {0} | failures: {1} | changed: {2} | missing: {3} | added by this order: {4}" -f $checks.Count, $failures.Count, $changed.Count, $missing.Count, $addedByThisOrder.Count
foreach ($f in $failures) { "  FAIL {0}: {1} :: {2}" -f $f.id, $f.what, $f.detail }
